"""
SQLAlchemy ORM models for the QR Code Genius application.

This module defines the database tables and their relationships using Flask-SQLAlchemy.
It includes models for User accounts and generated QR Codes, facilitating secure user
authentication and efficient management of QR code data.
"""

from datetime import datetime
from flask_login import UserMixin
from sqlalchemy.dialects.postgresql import UUID
import uuid

# Assuming db and bcrypt are initialized in app/extensions.py
# and imported into app/__init__.py, then made available here.
# For this file, we'll assume they are imported from a common place.
from app.extensions import db, bcrypt


class User(db.Model, UserMixin):
    """
    Represents a user account in the QR Code Genius application.

    This model stores user authentication details, including email,
    hashed password, and creation timestamp. It also manages the
    relationship with QR codes generated by the user.
    """
    __tablename__ = 'user'

    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(120), unique=True, nullable=False, index=True)
    password_hash = db.Column(db.String(128), nullable=False)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)

    # Relationship to QR_Code model
    qr_codes = db.relationship('QR_Code', backref='owner', lazy=True, cascade="all, delete-orphan")

    def __init__(self, email, password):
        """
        Initializes a new User instance.

        Args:
            email (str): The user's unique email address.
            password (str): The user's plain-text password, which will be hashed.
        """
        self.email = email
        self.set_password(password)

    def set_password(self, password):
        """
        Hashes the provided password and stores it.

        Args:
            password (str): The plain-text password to hash.
        """
        try:
            self.password_hash = bcrypt.generate_password_hash(password).decode('utf-8')
        except Exception as e:
            # Log the error or handle it appropriately
            raise RuntimeError(f"Failed to hash password: {e}")

    def check_password(self, password):
        """
        Checks if the provided plain-text password matches the stored hash.

        Args:
            password (str): The plain-text password to check.

        Returns:
            bool: True if the password matches, False otherwise.
        """
        try:
            return bcrypt.check_password_hash(self.password_hash, password)
        except Exception as e:
            # Log the error or handle it appropriately, e.g., return False for safety
            print(f"Error checking password for user {self.email}: {e}")
            return False

    def get_id(self):
        """
        Returns a unique identifier for the user, required by Flask-Login.

        Returns:
            str: The user's ID as a string.
        """
        return str(self.id)

    def __repr__(self):
        """
        Provides a string representation of the User object.

        Returns:
            str: A string in the format '<User %r>' where %r is the user's email.
        """
        return f'<User {self.email}>'


class QR_Code(db.Model):
    """
    Represents a generated QR code in the QR Code Genius application.

    This model stores details about each QR code, including its target URL,
    the filename of the generated image, and the timestamp of its creation.
    It also links each QR code to the user who generated it.
    """
    __tablename__ = 'qr_code'

    id = db.Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, unique=True, nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    target_url = db.Column(db.String(2048), nullable=False)  # URLs can be very long
    image_filename = db.Column(db.String(256), unique=True, nullable=False)
    generated_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)

    def __init__(self, user_id, target_url, image_filename):
        """
        Initializes a new QR_Code instance.

        Args:
            user_id (int): The ID of the user who generated the QR code.
            target_url (str): The URL encoded in the QR code.
            image_filename (str): The unique filename of the generated QR code image.
        """
        self.user_id = user_id
        self.target_url = target_url
        self.image_filename = image_filename

    def __repr__(self):
        """
        Provides a string representation of the QR_Code object.

        Returns:
            str: A string in the format '<QR_Code %r for User %r>'
                 where the first %r is the QR code's ID and the second is the user's ID.
        """
        return f'<QR_Code {self.id} for User {self.user_id}>'