from datetime import datetime
import os
import uuid
import validators

from flask import Blueprint, request, jsonify, current_app, url_for, send_file, abort
from flask_login import login_required, current_user

from app.extensions import db
from app.models.qr_code import QRCode
from app.utils import qr_generator, file_manager

qr_code_bp = Blueprint('qr_code', __name__, url_prefix='/api')

@qr_code_bp.route('/generate_qr', methods=['POST'])
@login_required
def generate_qr_code_route():
    """
    Generates a QR code for a given URL and stores it.

    Requires user authentication.
    Expects JSON payload with 'url' and optionally 'format' ('png' or 'svg').
    Saves the QR code image to disk and records its details in the database.

    Returns:
        A JSON response with success/error message, QR ID, download link,
        and other relevant details.
    """
    data = request.get_json()
    if not data or 'url' not in data:
        current_app.logger.warning(f"User {current_user.id} attempted QR generation without 'url'.")
        return jsonify({"message": "Missing 'url' in request body"}), 400

    target_url = data['url']
    qr_format = data.get('format', 'png').lower() # Default to PNG

    if qr_format not in ['png', 'svg']:
        current_app.logger.warning(f"User {current_user.id} requested invalid QR format: {qr_format}.")
        return jsonify({"message": "Invalid QR code format. Supported formats are 'png' and 'svg'."}), 400

    if not validators.url(target_url):
        current_app.logger.warning(f"User {current_user.id} provided invalid URL for QR generation: {target_url}.")
        return jsonify({"message": "Invalid URL provided. Please ensure it's a valid HTTP/HTTPS URL."}), 400

    try:
        # Generate a unique filename for the QR code image
        unique_id = uuid.uuid4()
        timestamp = datetime.utcnow().strftime('%Y%m%d%H%M%S')
        filename = f"qr_{current_user.id}_{timestamp}_{unique_id}.{qr_format}"

        # Generate and save the QR code image file
        # The qr_generator utility handles saving to the configured path
        image_full_path = qr_generator.generate_qr_code(target_url, qr_format, filename)

        # Record QR code details in the database
        new_qr = QRCode(
            user_id=current_user.id,
            target_url=target_url,
            image_filename=filename,
            qr_format=qr_format
        )
        db.session.add(new_qr)
        db.session.commit()

        # Construct the download URL for the newly generated QR code
        download_url = url_for('qr_code.download_qr_code', qr_id=new_qr.id, _external=True)

        current_app.logger.info(f"QR code generated for user {current_user.id}: {target_url} (ID: {new_qr.id})")
        return jsonify({
            "message": "QR code generated successfully.",
            "qr_id": str(new_qr.id),
            "target_url": target_url,
            "download_link": download_url,
            "format": qr_format,
            "generated_at": new_qr.generated_at.isoformat()
        }), 201

    except IOError as e:
        db.session.rollback() # Rollback database transaction if file saving failed
        current_app.logger.error(f"File system error during QR code generation for user {current_user.id}: {e}")
        return jsonify({"message": f"Failed to save QR code image: {e}"}), 500
    except Exception as e:
        db.session.rollback() # Rollback for any other unexpected errors
        current_app.logger.error(f"Unexpected error during QR code generation for user {current_user.id}: {e}")
        return jsonify({"message": f"An unexpected error occurred: {e}"}), 500

@qr_code_bp.route('/my_qrs', methods=['GET'])
@login_required
def get_user_qr_codes():
    """
    Retrieves a list of all QR codes generated by the authenticated user.

    Returns:
        A JSON response containing a list of QR code details, ordered by
        generation timestamp (most recent first).
    """
    try:
        # Query all QR codes belonging to the current user, ordered by generation time
        user_qrs = QRCode.query.filter_by(user_id=current_user.id).order_by(QRCode.generated_at.desc()).all()
        
        qr_list = []
        for qr in user_qrs:
            # Construct download URL for each QR code
            download_url = url_for('qr_code.download_qr_code', qr_id=qr.id, _external=True)
            qr_list.append({
                "id": str(qr.id),
                "target_url": qr.target_url,
                "generated_at": qr.generated_at.isoformat(), # ISO format for easy parsing on client side
                "image_filename": qr.image_filename,
                "format": qr.qr_format,
                "download_link": download_url
            })
        
        current_app.logger.info(f"Retrieved {len(qr_list)} QR codes for user {current_user.id}.")
        return jsonify(qr_list), 200

    except Exception as e:
        current_app.logger.error(f"Error retrieving QR codes for user {current_user.id}: {e}")
        return jsonify({"message": f"An unexpected error occurred: {e}"}), 500

@qr_code_bp.route('/delete_qr/<uuid:qr_id>', methods=['DELETE'])
@login_required
def delete_qr_code(qr_id):
    """
    Deletes a specific QR code generated by the authenticated user.

    Verifies that the QR code exists and belongs to the current user before deletion.
    Deletes both the database record and the associated image file from storage.

    Args:
        qr_id (uuid.UUID): The UUID of the QR code to delete.

    Returns:
        A JSON response with a success or error message.
    """
    try:
        # Find the QR code, ensuring it belongs to the current user
        qr_code = QRCode.query.filter_by(id=qr_id, user_id=current_user.id).first()

        if not qr_code:
            current_app.logger.warning(f"Attempted to delete non-existent or unauthorized QR code {qr_id} by user {current_user.id}.")
            return jsonify({"message": "QR code not found or you do not have permission to delete it."}), 404

        # Attempt to delete the image file from storage
        if not file_manager.delete_qr_image(qr_code.image_filename):
            # Log the error but proceed with DB deletion to maintain consistency if file deletion fails
            current_app.logger.error(f"Failed to delete QR code image file for QR ID {qr_id} ({qr_code.image_filename}). "
                                     "Proceeding with database record deletion.")
            # Depending on business logic, you might choose to return a 500 here
            # if file deletion is considered critical